### ISSUE TITLE
Latest Versions of snowy firmware not available

### ISSUE THREAD

**Issue by HalosGhost** [MarSoft/pebble-firmware-utils#14]
The latest version of the 3.x firmware (the one I am now running on my PTS) is 3.10.1, but ``downloadFirmware.py`` seems to think the latest is 3.6.1. Has 3.10 just not been publicly released for download?

**Comment by MarSoft** [comment]
Fixed.
Personally I use `getver.sh` script, but it lacks the same problem and requires manual intervention to work it around; will fix it soon as well.

**Comment by HalosGhost** [comment]
Hmm, perhaps I am doing this wrong:

``` console
Downloading version 3.10.1 for HW snowy_s3
--2016-03-27 18:44:10--  https://pebblefw.s3.amazonaws.com/pebble/snowy_s3/release-v3.7/pbz/Pebble-3.10.1-snowy_s3.pbz
Resolving pebblefw.s3.amazonaws.com (pebblefw.s3.amazonaws.com)... 54.231.82.98
Connecting to pebblefw.s3.amazonaws.com (pebblefw.s3.amazonaws.com)|54.231.82.98|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-03-27 18:44:10 ERROR 403: Forbidden.
```

Any idea what went wrong? (And thank you for all the work!)

**Comment by MarSoft** [comment]
Fixed. Now you can download it like this:
```
downloadFirmware.py 3.8 snowy_s3
```
3.8 is a version group, this tool will download latest available version for requested version group.
