### ISSUE TITLE
wikipage: greek hebrew github link on wiki/Language-Packs is 404

### ISSUE THREAD

**Issue by meldra** [MarSoft/pebble-firmware-utils#15]
I expect it should be https://github.com/MarSoft/pebble-firmware-utils/raw/builds/langs/plain/gr+hb1.pbl but I don't know if this was intentional (maybe it is problematic?) so didn't edit the link in the page. But fyi...

**Comment by MarSoft** [comment]
Thanks for the report. I have already rebuilt that problematic pack and now have uploaded a fixed version under original gr+hb.pbl name. Please test if it works for you.

**Comment by MarSoft** [comment]
Considering fixed

**Comment by MarSoft** [comment]
@meldra, please reopen if the problem persists.
