### ISSUE TITLE
How to add languages support manually?

### ISSUE THREAD

**Issue by ybogdanov** [MarSoft/pebble-firmware-utils#9]
Hi, Semen!

Any hints on how you did [this](http://pebblebits.com/firmware/)? I want to add Cyrillic support on my own every time Pebble ships a new firmware.

For example, I found the latest patched firmware v3.2.1 [here](http://4pda.ru/forum/index.php?showtopic=526970&st=1180) but yesterday Pebble released v3.3 and now there is annoying update notification in iOS app.

As far as I figured it out, `tintin_fw.bin` should be patched. How?

Thanks.

**Comment by MarSoft** [comment]
Tintin_fw.bin should be patched with patcher.py script using StringFixer.pbp patch, although it is not mandatory.
Then you should unpack resources (unpackFirmware.py), replace corresponding font resources (according to fonts.txt) with localized versions from PebbleBits, repack resource bundle (packResources.sh), and then rebuild firmware (repackFirmware.py).
BTW, I already published v3.3 builds.

**Comment by ybogdanov** [comment]
Thanks!

> BTW, I already published v3.3 builds.
Where?

**Comment by MarSoft** [comment]
http://forums.getpebble.com/discussion/comment/152925/#Comment_152925

чт, 20 авг. 2015 г. в 11:37, Yuriy Bogdanov <notifications@github.com>:

**Comment by ybogdanov** [comment]
Cool, thanks!
